version: "3.7"
services:
  web:
    build: web
    networks:
      - book_network
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    networks:
      - book_network
  db:
    image: postgres:12
    restart: always
    networks:
      - book_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=books
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: api
    restart: always
    networks:
      - book_network
    environment:
      - ENV=prod

networks:
  book_network:
volumes:
  postgres_data:
